### ISSUE TITLE
Tensorboard failed to run. [solved on running container]

### ISSUE THREAD

**Issue by robbisg** [floydhub/dl-docker#49]
Hi all,

I tried to run tensorboard on my docker build (I excluded opencv because it fails and I don't need it). 
I came into this exception running tensorboard --logdir foo/

I had the attached Traceback.
I solved the issue, using this solution https://github.com/coursera-dl/coursera-dl/issues/554 and running
```bash
pip install --upgrade html5lib==1.0b8
```
So I think I need to update my Dockerfile to include this lib.

```python
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/tensorboard.py", line 34, in <module>
    from tensorflow.tensorboard.backend import server
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/backend/server.py", line 37, in <module>
    from tensorflow.tensorboard.backend import handler
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/backend/handler.py", line 43, in <module>
    from tensorflow.tensorboard.plugins import REGISTERED_PLUGINS
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/plugins/__init__.py", line 20, in <module>
    from tensorflow.tensorboard.plugins.projector.plugin import ProjectorPlugin
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 27, in <module>
    from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 27, in <module>
    from tensorflow.contrib import factorization
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 66, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 269, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.classifier import Classifier
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/classifier.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.pandas_io import extract_pandas_data
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/pandas_io.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.queues import feeding_functions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.tensorflow_dataframe import TensorFlowDataFrame
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/tensorflow_dataframe.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.transforms import in_memory_source
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/transforms/in_memory_source.py", line 22, in <module>
    from tensorflow.contrib.learn.python.learn.dataframe.queues import feeding_functions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/dataframe/queues/feeding_functions.py", line 38, in <module>
    import pandas as pd
  File "/usr/lib/python2.7/dist-packages/pandas/__init__.py", line 44, in <module>
    from pandas.io.api import *
  File "/usr/lib/python2.7/dist-packages/pandas/io/api.py", line 10, in <module>
    from pandas.io.html import read_html
  File "/usr/lib/python2.7/dist-packages/pandas/io/html.py", line 25, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 306, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

**Comment by Obeyed** [comment]
I made a pull request for this (#51)
