### ISSUE TITLE
GPU install failing at tornado module

### ISSUE THREAD

**Issue by hlfshell** [floydhub/dl-docker#84]
While running the command
`docker build -t floydhub/dl-docker:gpu -f Dockerfile.gpu .` within the repos, it fails during the installation of the tornado module in python. Below is the relevant stack trace.

```
Collecting tornado>=4.0 (from ipykernel)
  Downloading tornado-5.0.tar.gz (504kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dS1ilp/tornado/setup.py", line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dS1ilp/tornado/
The command '/bin/sh -c pip --no-cache-dir install --upgrade ipython && 	pip --no-cache-dir install 		Cython 		ipykernel 		jupyter 	path.py 		Pillow 		pygments 		six 		sphinx 		wheel 		zmq 		&& 	python -m ipykernel.kernelspec' returned a non-zero code: 1
```

Unsure where to go from here. Thanks!

**Comment by wardheij** [comment]
I encountered the same problem.

**Comment by cathray** [comment]
same :(

**Comment by KSchopmeyer** [comment]
Same issue with pywbem pip package. The python2 code in this package uses M2Crypto as ssl package for historical reasons

**Comment by tristankpka** [comment]
Is there any fix to this issue as it is closed ?

**Comment by babazaroni** [comment]
Same problem for me.  Joining this thread to monitor for solution.

**Comment by tristankpka** [comment]
Same problem, joining the thread.

**Comment by ptiagi** [comment]
I just resolved this issue by upgrading my python 2.7 to 2.7.10.
Try running the following commands from you virtual environment:
pyenv install 2.7.10
pyenv global 2.7.10

**Comment by opencoca** [comment]
@ptiagi That's a great fix if the issue was inside a virtual environment. would need to install virtualenv and along with it pyenv. As things are now an other fix would be to grab python from https://python.org and install it. 

Popping the following into my Dockerfile.gpu overcame the up-to-date SSL module issue. 
```
ARG PYTHON_BASEDEPS="build-essential python-pip"
ARG PYTHON_BUILDDEPS="libbz2-dev \
   libc6-dev \
   libgdbm-dev \
   libncursesw5-dev \
   libreadline-gplv2-dev \
   libsqlite3-dev \
   libssl-dev \
   tk-dev"


ARG PYTHON_TARFILE="Python-2.7.9.tgz"
ARG PYTHON_TARHOST="https://www.python.org/ftp/python/2.7.9"
ARG PYTHON_SRCDIR="Python-2.7.9"

RUN apt-get update
RUN apt-get install -y ${PYTHON_BASEDEPS} ${PYTHON_BUILDDEPS}

RUN wget "${PYTHON_TARHOST}/${PYTHON_TARFILE}"
RUN tar xvf ${PYTHON_TARFILE}
 
RUN cd ${PYTHON_SRCDIR} && \
   ./configure && \
   make && \
   make install
```

**Comment by opencoca** [comment]
For a working build see https://github.com/opencoca/dl-docker/commit/de9050f4376964eb039a93c47aade0db7bcf5f8f

**Comment by abdallahmohammed197** [comment]
facing the same problem

**Comment by nwatab** [comment]
Same problem after resolving #86 on Ubuntu 16, but https://github.com/floydhub/dl-docker/issues/84#issuecomment-377308528 worked.

**Comment by OneCodeMonkey** [comment]
facing the same problem as well. Tried several times still not solved :(
